version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - mispay
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS: 'admin'
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  email-notification-service:
    image: email-notification-service:latest
    build: .
    networks:
      - mispay
    environment:
      SENDER_EMAIL: 'msajawalsial@gmail.com'
      RABBITMQ_USER: 'admin'
      RABBITMQ_PASSWORD: 'admin'
      RABBITMQ_HOST: rabbitmq:5672
      RABBITMQ_QUEUE_NAME: 'emails'
    depends_on:
      - rabbitmq

networks:
  mispay:
    driver: bridge
